# 1. Usa una imagen base oficial de Python
FROM python:3.9-slim

# 2. Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# 3. Copia los archivos del proyecto al contenedor
COPY . /app

# 4. Instala las dependencias desde requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# 5. Exponer el puerto en el que corre la aplicación (Flask usa 8080 por defecto)
EXPOSE 8080

# 6. Define el comando para ejecutar la aplicación
CMD ["python", "app.py"]